apiVersion: v1
kind: Service
metadata:
  name: traffic-counters-map-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: traffic-counters-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-counters-map-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traffic-counters-map
  template:
    metadata:
      labels:
        app: traffic-counters-map
    spec:
      containers:
      - name: traffic-counters-map
        image: ghcr.io/forumviriumhelsinki/traffic-counters-map:v0.1.0
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-counters-map-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - traffic-counters-map.example.fi
    secretName: traffic-counters-map-tls
  rules:
  - host: traffic-counters-map.example.fi
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: traffic-counters-map-service
            port:
              number: 80
